version: "2"
services:
  app:
    image: golang:1.15-alpine
    volumes:
      - ./back:/app
    working_dir: /app
    command: go run main.go
    ports:
      - "8080:8080"
  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: example
    ports:
      - "3306:3306"
    command:
      [
        "mysqld",
        "--character-set-server=utf8mb4",
        "--default-authentication-plugin=mysql_native_password",
      ]
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      - PMA_ARBITRARY=1
      - PMA_HOST=db
      - PMA_USER=root
      - PMA_PASSWORD=example
    ports:
      - 8081:80
    volumes:
      - /sessions
