@startuml

package 認証済パッケージ{
    (登録する)
    (ログインする)
    (ログアウトする)
    (ブログを公開する)
    (ブログを下書きにする)
    (ブログを編集する)
    (ブログに画像を貼り付ける)
    (ブログにリンクを貼る)
    (ブログをプレビューで見る)
    (ブログを一覧で見る)
    (ブログを削除する)
    (ブログにコメントする)
    (ブログにコメントにコメントする)
}

package 未認証パッケージ{
    (ブログを見る)
    (ブログをシェアする)
}

@enduml