@startuml
left to right direction

:投稿者:
:ユーザー:

(親コメント)
(子コメント)
(投稿)
(下書き)
(公開)
(投稿方法)
(スライド)
(マークダウン)

投稿者 o-- 投稿
投稿 <|-- 下書き
投稿 <|-- 公開
投稿 --> 投稿方法
投稿方法 <|-- スライド
投稿方法 <|-- マークダウン
投稿者 --|> ユーザー

投稿 o-- 親コメント
ユーザー o-- 親コメント
親コメント o-- 子コメント

@enduml