openapi: 3.0.2
info:
  title: k42un0k0blog
  version: 1.0.0
servers:
  - url: http://localhost:8080
    description: development env
paths:
  /sign_in:
    post:
      description: Sign In
      operationId: signIn
      requestBody:
        content:
          application/json; charset=utf-8:
            schema:
              $ref: "#/components/schemas/AuthRequest"
            example:
              username: "test@test.com"
              password: "password"
      responses:
        "200":
          description: successfully authorized
          content:
            application/json; charset=utf-8:
              schema:
                $ref: "#/components/schemas/Auth"
  /users:
    $ref: ./paths/users.yml
  /users/{id}:
    $ref: ./paths/users_id.yml
  /users/{id}/password:
    $ref: ./paths/users_id_password.yml
  /blogs:
    $ref: ./paths/blogs.yml

components:
  schemas:
    Auth:
      type: object
      description: authorized response
      properties:
        expire:
          type: string
          example: "2016-03-19T11:44:52+08:00"
        token:
          type: string
          example: "abcdefgh12345678"
    AuthRequest:
      type: object
      properties:
        username:
          type: string
        password:
          type: string
      required:
        - username
        - password
    UserResponse:
      $ref: ./components/user_response.yml
    BlogResponse:
      $ref: ./components/blog_response.yml